// fronted/src/components/Navbar.jsx
import React from 'react';
import { Link, NavLink } from 'react-router-dom';

function NavbarComponent({ user }) {
  return (
    <nav className="navbar navbar-expand-lg bg-body-tertiary">
      <div className="container-fluid">
        <Link className="navbar-brand" to="/">Navbar</Link>
        <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span className="navbar-toggler-icon"></span>
        </button>
        <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div className="navbar-nav me-auto">
            <NavLink className="nav-link" to="/requests">Requests</NavLink>
            <NavLink className="nav-link" to="/users">Users</NavLink>
            <NavLink className="nav-link" to="/notes">Notes</NavLink>
          </div>
          <div className="navbar-nav">
            {user ? (
              <div className="nav-item dropdown">
                <a className="nav-link dropdown-toggle d-flex align-items-center" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {user.photo ? (
                    <img src={user.photo} className="rounded-circle" style={{ width: '30px', height: '30px' }} alt="Profile" />
                  ) : (
                    <span className="rounded-circle bg-secondary d-inline-block text-center text-white" style={{ width: '30px', height: '30px', lineHeight: '30px' }}>
                      {user.name.charAt(0)}
                    </span>
                  )}{" "}
                  <span className="ms-2">{user.name}</span>
                </a>
                <ul className="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><NavLink className="dropdown-item" to="/profile">Edit Profile</NavLink></li>
                  <li><hr className="dropdown-divider" /></li>
                  <li><NavLink className="dropdown-item" to="/logout">Logout</NavLink></li>
                </ul>
              </div>
            ) : (
              <NavLink className="nav-link btn btn-outline-primary" to="/login">Login</NavLink>
            )}
          </div>
        </div>
      </div>
    </nav>
  );
}

export default NavbarComponent;

// front/src/components/Navbar.vue
<template>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <RouterLink class="navbar-brand" to="/">Bulls and Cows</RouterLink>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <RouterLink class="nav-link active" aria-current="page" to="/">Home</RouterLink>
          </li>
          <li class="nav-item">
            <RouterLink class="nav-link" to="/features">Features</RouterLink>
          </li>
          <li class="nav-item">
            <RouterLink class="nav-link" to="/pricing">Pricing</RouterLink>
          </li>
          <li class="nav-item">
            <RouterLink class="nav-link disabled" aria-disabled="true" to="#">Disabled</RouterLink>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <button class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="@/assets/profile-placeholder.svg" alt="Profile Picture" class="profile-pic" />
              <span class="username">User Name</span>
            </button>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li><RouterLink class="dropdown-item" to="/profile">Edit Profile</RouterLink></li>
              <li><RouterLink class="dropdown-item" to="/login">Login</RouterLink></li>
              <li><RouterLink class="dropdown-item" to="/logout">Logout</RouterLink></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script setup>
import { RouterLink } from 'vue-router';
</script>

<style scoped>
.profile-pic {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  cursor: pointer;
  margin-right: 5px;
}

.username {
  margin-left: 5px;
}
</style>
